@startuml container

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <office/users/users.puml>

AddRelTag("async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DashedLine())

title Deposite - Container - TO BE

Person(client, "Клиент")

Person(deposite, "Управление обслуживанием депозитных продуктов", $sprite="users")
Person(credit, "Управление обслуживанием кредитных продуктов", $sprite="users")
Person(call, "Кол-центр", $sprite="users")


System(site, "Сайт", "React.js\nPHP")

System_Boundary(bank, "Интернет-банк") {
    Container(bank_app, "APP", "ASP.NET")
    Container(bank_db, "DB", "MS SQL")
    Container(bank_kafka, "Kafka")
    Container(bank_orders, "Orders", "Сервис заявок")
}

System(crm, "CRM", "React.js\nJava Spring Boot\nPostgreSQL")

System_Boundary(abs, "АБС") {
    Container(abs_app, "APP", "Delphi")
    Container(abs_db, "DB", "Oracle")
}

Container(sms, "SMS-шлюз")
System_Ext(telecom, "Телеком-оператор")


Rel(client, site, "Предложения по депозитам\nЗаявка на депозит")
Rel(client, bank_app, "Предложения по депозитам\nЗаявка на депозит")
Rel(client, call, "Заявка на депозит")

Rel(call, crm, "Заявка на депозит")
Rel(site, crm, "Заявка на депозит")

Rel(bank_app, bank_kafka, "Заявка на депозит")
Rel(bank_kafka, bank_orders, "Заявки на депозит", $tags="async")

Rel(bank_app, abs_db, "Предложения по депозитам")
Rel(crm, abs_db, "Заявка на депозит")
Rel(site, abs_db, "Предложения по депозитам")
Rel(bank_orders, abs_db, "Заявки на депозит")
Rel(deposite, abs_app, "Обработка заявок\nЗагрузка ставок по депозитам")
Rel(credit, abs_app, "Расчет кредитного риска\nЗагрузка кредитных рисков")

Rel(abs_app, sms, "SMS: Депозит одобрен")
Rel(bank_app, sms, "Код подтверждения")

Rel(sms, telecom, "")

@enduml
