@startuml container

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <office/users/users.puml>

AddRelTag("async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DashedLine())

title Deposite - Container - TO BE

Person(client, "Клиент")

Person(deposite, "Управление обслуживанием депозитных продуктов", $sprite="users")
Person(call, "Кол-центр", $sprite="users")
Person(call_partner, "Кол-центр\nпартнера", $sprite="users")


System(crm, "CRM", "React.js\nJava Spring Boot\nPostgreSQL")

System_Boundary(abs, "АБС") {
    Container(abs_app, "APP", "Delphi")
    Container(abs_db, "DB", "Oracle")
}


Rel(client, call, "Запрос ставок")
Rel(client, call_partner, "Запрос ставок")

Rel(call, crm, "Получение ставок")
Rel(crm, abs_db, "Получение ставок")

Rel(deposite, abs_app, "Загрузка ставок по депозитам")
Rel(abs_app, call_partner, "Новые ставки в виде файла почтой")

@enduml
