@startuml container

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include <office/users/users.puml>

AddRelTag("async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DashedLine())

title Deposite - Container - TO BE

Person(client, "Клиент")

Person(service, "Управление обслуживанием в сети отделений", $sprite="users")
Person(credit, "Управление обслуживанием кредитных продуктов", $sprite="users")


System(site, "Сайт", "React.js\nPHP")

System_Boundary(bank, "Интернет-банк") {
    Container(bank_app, "APP", "ASP.NET")
    Container(bank_db, "DB", "MS SQL")
}

System_Boundary(abs, "АБС") {
    Container(abs_app, "APP", "Delphi")
    Container(abs_db, "DB", "Oracle")
}

System_Boundary(credit_line, "Кредитный конвейер") {
    Container(credit_line_app, "APP", "Camunda")
    Container(credit_line_db, "DB", "Oracle")
}

System_Boundary(credit_score, "Система кредитного скоринга") {
    Container(credit_score_app, "APP", "Python")
    Container(credit_score_db, "DB", "PostgreSQL")
}
System_Ext(credit_history, "Бюро кредитных историй")
Container(sms, "SMS-шлюз")
System_Ext(telecom, "Телеком-оператор")


Rel(client, site, "Предложения по кредитам\nЗаявка на кредит")
Rel(client, bank_app, "Предложения по кредитам\nЗаявка на кредит")
Rel(client, service, "Заявка на кредит")

Rel(service, abs_app, "Заявка на кредит\nПолучение драфтовых заявок")

Rel(abs_db, credit_line_db, "Передача заявок", "Раз в день", $tags="async")
Rel(credit, credit_line_app, "Обработка заявок")
Rel(site, credit_line_app, "Ставки по кредитам")
Rel(bank_app, credit_line_app, "Ставки по кредитам\nПредодобренные кредиты\nЗаявка по предодобрению")

Rel(credit_line_app, credit_score_app, "Получить оценку клиента")
Rel(abs_db, credit_score_db, "Данные клиента\nИстория платежей по кредитам", "Раз в день", $tags="async")

Rel(site, abs_db, "Заявка на кредит\nЗаявка в виде драфта")
Rel(bank_app, abs_db, "Заявка на кредит")
Rel_Up(credit_line_db, abs_db, "Передача статусов, для зачисления денег", "Раз в день", $tags="async")

Rel(credit_score_app, credit_history, "Получить историю")

Rel_D(credit_line_app, sms, "Кредит одобрен")
Rel(site, sms, "Приглашение в офис")

Rel(sms, telecom, "")

@enduml
