@startuml context

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include <office/users/users.puml>

AddRelTag("async", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DashedLine())

title Deposite - Context - TO BE

Person(client, "Клиент")

Person(service, "Управление обслуживанием в сети отделений", $sprite="users")
Person(credit, "Управление обслуживанием кредитных продуктов", $sprite="users")


System_Boundary(standart, "Банк Стандарт") {
    System(site, "Сайт", "React.js\nPHP")
    System(bank, "Интернет-банк", "ASP.NET\nMS SQL")
    System(abs, "АБС", "Delphi\nPL-SQL\nOracle")
    System(credit_line, "Кредитный конвейер", "Camunda\nOracle")
    System(credit_score, "Система кредитного скоринга", "Python\nPostgreSQL")
    System(sms, "SMS-шлюз")
}
System_Ext(credit_history, "Бюро кредитных историй")
System_Ext(telecom, "Телеком-оператор")


Rel(client, site, "Предложения по кредитам\nЗаявка на кредит")
Rel(client, bank, "Предложения по кредитам\nЗаявка на кредит")
Rel(client, service, "Заявка на кредит")

Rel(service, abs, "Заявка на кредит\nПолучение драфтовых заявок")

Rel(abs, credit_line, "Передача заявок", "Раз в день", $tags="async")
Rel(credit, credit_line, "Обработка заявок")
Rel(site, credit_line, "Ставки по кредитам")
Rel(bank, credit_line, "Ставки по кредитам\nПредодобренные кредиты\nЗаявка по предодобрению")

Rel(credit_line, credit_score, "Получить оценку клиента")
Rel(abs, credit_score, "Данные клиента\nИстория платежей по кредитам", "Раз в день", $tags="async")

Rel(site, abs, "Заявка на кредит\nЗаявка в виде драфта")
Rel(bank, abs, "Заявка на кредит")
Rel(credit_line, abs, "Передача статусов, для зачисления денег", "Раз в день", $tags="async")

Rel(credit_score, credit_history, "Получить историю")

Rel(credit_line, sms, "Кредит одобрен")
Rel(site, sms, "Приглашение в офис")

Rel(sms, telecom, "")

@enduml
